In [1]:
import pandas as pd
import numpy as np
import csv
import glob
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
ALL_SONG_PATH="D:/CSE519/Project/billboard_w_new_features_v7.csv"
FEATURE_ROOT="D:/CSE519/Project/song_feature/"
NEW_FEATURE_CSV_PATH="D:/CSE519/Project/allsong_feature.csv"

# Read all song information and drop duplicates

In [4]:
allSong= pd.read_csv(ALL_SONG_PATH, encoding='latin-1')
allSong.sort_values(by=["weekid"], ascending=True)
allSong.drop_duplicates(subset=['songid'], keep='first', inplace=True )
allSong.shape

(27278, 17)

# preprocess the all song data frame  with "/" in song name

In [5]:
def split_funct(x):
    song=x['song']
    if "/" in song:
        return song.split("/")
    else:
        return []
allSong['split']= allSong.apply(lambda x: split_funct(x), axis=1)

# double check the split function works

In [6]:
withSplit=allSong['split'].map(lambda x: len(x)>=2)
print(allSong[withSplit].shape)
withNoSplit=allSong['split'].map(lambda x: x==[])
print(allSong[withNoSplit].shape)
allSong.head()
withSlash = allSong['song'].map(lambda x: "/" in x)
print(allSong[withSlash].shape)
withNoSlash=allSong['song'].map(lambda x: "/" not in x)
print(allSong[withNoSlash].shape)

(263, 18)
(27015, 18)
(263, 18)
(27015, 18)

# All features that needs to merge

In [7]:
def process_feature_name(list_feature_name):
    new_list_feature=[]
    for file in list_feature_name:
        a=file.replace('D:/CSE519/Project/song_feature\songs-','')
        b=a.replace(".csv",'')     
        new_list_feature.append(b)
    return new_list_feature

list_feature_name=glob.glob(FEATURE_ROOT+"*.csv")
print(len(list_feature_name))
feature_name=process_feature_name(list_feature_name)
print(len(feature_name))

26
26

In [8]:
def check_split_func(song_row, featureSong, featureArtist, feature_name):
    split_song =song_row['split']
    if ((featureSong in split_song) & (featureArtist==song_row['performer'])):
        song_row[feature_name]=1   
    
def slash_func(featureSong_row,  allSong, feature_name):
    featureSong=featureSong_row['song']
    featureArtist=featureSong_row['artist']
    if "/" not in featureSong:
        if (allSong.loc[ (allSong.song==featureSong)  & (allSong.performer==featureArtist) ].shape[0]!=0):
            allSong.loc[ ((allSong.song == featureSong) & (allSong.performer==featureArtist)) , feature_name] = 1
        else:            
            allSong.apply(lambda x: check_split_func(x, featureSong, featureArtist, feature_name), axis=1)
    if "/" in featureSong:
        featureSongs_array=featureSong.split("/")
        for songs in featureSongs_array:
            if (allSong.loc[(allSong.song==featureSong)  & (allSong.performer==featureArtist)].shape[0]!=0):
                allSong.loc[((allSong.song == featureSong) & (allSong.performer==featureArtist)), feature_name] = 1
            else:            
                allSong.apply(lambda x: check_split_func(x, songs,featureArtist, feature_name), axis=1)

In [11]:
for idx, feature in enumerate (feature_name):    
    feature_df=pd.read_csv(list_feature_name[idx], encoding='latin-1')
    allSong[feature]=0
    feature_df.apply(lambda x: slash_func(x, allSong,feature), axis=1)
    print(idx)

In [ ]:
allSong.to_csv(NEW_FEATURE_CSV_PATH, index=False)

In [ ]:
allSong.shape

In [31]:
allSong=pd.read_csv(NEW_FEATURE_CSV_PATH,sep='\t')
allSong.drop("Unnamed: 0", inplace=True,axis=1)
allSong.shape

(27278, 44)

In [20]:
allSong.head(1)

,url,weekid,week_position,song,performer,songid,instance,previous_week_position,peak_position,weeks_on_chart,...,karaoke,lullabies,mtvawards,phonecall,politicians,sportingevents,tvshow,weddings,wonoscars,wordcup
0,http://www.billboard.com/charts/hot-100/1990-0...,1990-05-05,84,"""B"" Girls",Young And Restless,"""B"" GirlsYoung And Restless",1,NaN,54,15,...,0,0,0,0,0,0,0,0,0,0

# song features and the matches we found

In [21]:
for idx, feature in enumerate (feature_name):    
    feature_df=pd.read_csv(list_feature_name[idx], encoding='latin-1')
    print ("the songs with feature "+ feature+ " "+ str(feature_df.shape))
    allsong_with_feature=allSong.loc[allSong[feature]==1]
    print("the matches that we finally find out "+ str(allsong_with_feature.shape))

the songs with feature artistdied (46, 2)
the matches that we finally find out (22, 44)
the songs with feature christmas (225, 2)
the matches that we finally find out (18, 44)
the songs with feature church (102, 2)
the matches that we finally find out (4, 44)
the songs with feature classical (73, 2)
the matches that we finally find out (0, 44)
the songs with feature commercials (699, 2)
the matches that we finally find out (272, 44)
the songs with feature concerts (35, 2)
the matches that we finally find out (13, 44)
the songs with feature easter (20, 2)
the matches that we finally find out (0, 44)
the songs with feature fourthofjuly (25, 2)
the matches that we finally find out (6, 44)
the songs with feature funerals (39, 2)
the matches that we finally find out (11, 44)
the songs with feature graduations (71, 2)
the matches that we finally find out (38, 44)
the songs with feature grammys (450, 2)
the matches that we finally find out (244, 44)
the songs with feature halloween (35, 2)
the matches that we finally find out (9, 44)
the songs with feature inmovieclueless (15, 2)
the matches that we finally find out (7, 44)
the songs with feature inmovies (2239, 2)
the matches that we finally find out (633, 44)
the songs with feature inplays (332, 2)
the matches that we finally find out (16, 44)
the songs with feature intvshows (616, 2)
the matches that we finally find out (183, 44)
the songs with feature karaoke (34, 2)
the matches that we finally find out (25, 44)
the songs with feature lullabies (37, 2)
the matches that we finally find out (1, 44)
the songs with feature mtvawards (110, 2)
the matches that we finally find out (57, 44)
the songs with feature phonecall (36, 2)
the matches that we finally find out (9, 44)
the songs with feature politicians (55, 2)
the matches that we finally find out (22, 44)
the songs with feature sportingevents (98, 2)
the matches that we finally find out (31, 44)
the songs with feature tvshow (205, 2)
the matches that we finally find out (41, 44)
the songs with feature weddings (82, 2)
the matches that we finally find out (39, 44)
the songs with feature wonoscars (55, 2)
the matches that we finally find out (16, 44)
the songs with feature wordcup (23, 2)
the matches that we finally find out (1, 44)

In [64]:
df_array=[]
for idx, feature in enumerate (feature_name):    
    allsong_with_feature=allSong.loc[allSong[feature]==1]
    df_array.append(allsong_with_feature)
#     print("the matches that we finally find out "+ str(allsong_with_feature.shape))

In [65]:
print(feature_name[0])

columns_to_drop=feature_name[1:25]
df_mody=df_array[0].drop(columns_to_drop, axis=1)
df_mody

artistdied

,url,weekid,week_position,song,performer,songid,instance,previous_week_position,peak_position,weeks_on_chart,year,week,jump_time,max_jump_duration,strict_rule,lenient_rule,all_time_greatest_artist,split,artistdied,wordcup
117,http://www.billboard.com/charts/hot-100/1980-1...,1980-11-01,38,(Just Like) Starting Over,John Lennon,(Just Like) Starting OverJohn Lennon,1,NaN,1,22,1980,44,0,0,51,47,0,[],1,0
163,http://www.billboard.com/charts/hot-100/1968-0...,1968-01-27,67,(Sittin' On) The Dock Of The Bay,Otis Redding,(Sittin' On) The Dock Of The BayOtis Redding,1,NaN,1,16,1968,4,0,0,69,62,0,[],1,0
293,http://www.billboard.com/charts/hot-100/1982-1...,1982-10-30,81,1999,Prince,1999Prince,1,NaN,12,30,1982,43,3,6321,66,0,1,[],1,0
442,http://www.billboard.com/charts/hot-100/1965-0...,1965-01-30,70,A Change Is Gonna Come,Sam Cooke,A Change Is Gonna ComeSam Cooke,1,NaN,31,7,1965,4,0,0,64,0,0,[],1,0
3891,http://www.billboard.com/charts/hot-100/2013-0...,2013-06-08,26,Clouds,Zach Sobiech,CloudsZach Sobiech,1,NaN,26,2,2013,23,0,0,36,0,0,[],1,0
5196,http://www.billboard.com/charts/hot-100/1997-1...,1997-12-20,96,Doin' Time,Sublime,Doin' TimeSublime,1,NaN,87,7,1997,51,0,0,53,57,0,[],1,0
5216,http://www.billboard.com/charts/hot-100/1958-1...,1958-11-22,93,Donna,Ritchie Valens,DonnaRitchie Valens,1,NaN,2,23,1958,47,0,0,0,53,0,[],1,0
7009,http://www.billboard.com/charts/hot-100/1995-1...,1995-12-30,10,Free As A Bird,The Beatles,Free As A BirdThe Beatles,1,NaN,6,11,1995,52,0,0,48,0,1,[],1,0
7324,http://www.billboard.com/charts/hot-100/1971-0...,1971-09-11,80,Get It While You Can,Janis Joplin,Get It While You CanJanis Joplin,1,NaN,78,2,1971,36,0,0,42,29,0,[],1,0
9526,http://www.billboard.com/charts/hot-100/1997-0...,1997-04-26,2,Hypnotize,The Notorious B.I.G.,HypnotizeThe Notorious B.I.G.,1,NaN,1,20,1997,17,0,0,77,68,0,[],1,0
11090,http://www.billboard.com/charts/hot-100/1974-0...,1974-03-02,73,I'll Have To Say I Love You In A Song,Jim Croce,I'll Have To Say I Love You In A SongJim Croce,1,NaN,9,14,1974,9,0,0,51,44,0,[],1,0
11787,http://www.billboard.com/charts/hot-100/1959-0...,1959-02-21,82,It Doesn't Matter Anymore,Buddy Holly,It Doesn't Matter AnymoreBuddy Holly,1,NaN,13,14,1959,8,0,0,0,41,0,[],1,0
14946,http://www.billboard.com/charts/hot-100/1971-0...,1971-01-30,94,Me And Bobby McGee,Janis Joplin,Me And Bobby McGeeJanis Joplin,1,NaN,1,15,1971,4,0,0,68,44,0,[],1,0
15009,http://www.billboard.com/charts/hot-100/1972-0...,1972-08-12,90,Melissa,The Allman Brothers Band,MelissaThe Allman Brothers Band,1,NaN,86,2,1972,32,0,0,54,0,0,[],1,0
16361,http://www.billboard.com/charts/hot-100/1984-0...,1984-01-21,36,Nobody Told Me,John Lennon,Nobody Told MeJohn Lennon,1,NaN,5,14,1984,3,0,0,45,0,0,[],1,0
18148,http://www.billboard.com/charts/hot-100/1996-0...,1996-03-23,11,Real Love,The Beatles,Real LoveThe Beatles,1,NaN,11,7,1996,12,0,0,47,0,1,[],1,0
23747,http://www.billboard.com/charts/hot-100/1973-1...,1973-11-17,79,Time In A Bottle,Jim Croce,Time In A BottleJim Croce,1,NaN,1,15,1973,46,0,0,57,51,0,[],1,0
24957,http://www.billboard.com/charts/hot-100/1981-0...,1981-03-28,77,Watching The Wheels,John Lennon,Watching The WheelsJohn Lennon,1,NaN,10,17,1981,13,0,0,47,59,0,[],1,0
25523,http://www.billboard.com/charts/hot-100/1977-1...,1977-12-03,83,What's Your Name,Lynyrd Skynyrd,What's Your NameLynyrd Skynyrd,1,NaN,13,18,1977,48,0,0,0,44,0,[],1,0
26292,http://www.billboard.com/charts/hot-100/1981-0...,1981-01-17,36,Woman,John Lennon,WomanJohn Lennon,1,NaN,2,20,1981,3,0,0,70,36,0,[],1,0
26745,http://www.billboard.com/charts/hot-100/1989-0...,1989-01-21,85,You Got It,Roy Orbison,You Got ItRoy Orbison,1,NaN,9,18,1989,3,0,0,67,0,0,[],1,0
26798,http://www.billboard.com/charts/hot-100/2002-1...,2002-10-19,55,You Know You're Right,Nirvana,You Know You're RightNirvana,1,NaN,45,20,2002,42,0,0,58,30,0,[],1,0

In [33]:
columns_to_drop=feature_name[1:25]
allSong.loc[allSong['songid']=="(Sittin' On) The Dock Of The BayOtis Redding"].drop(columns_to_drop, axis=1)

,url,weekid,week_position,song,performer,songid,instance,previous_week_position,peak_position,weeks_on_chart,year,week,jump_time,max_jump_duration,strict_rule,lenient_rule,all_time_greatest_artist,split,artistdied,wordcup
163,http://www.billboard.com/charts/hot-100/1968-0...,1968-01-27,67,(Sittin' On) The Dock Of The Bay,Otis Redding,(Sittin' On) The Dock Of The BayOtis Redding,1,NaN,1,16,1968,4,0,0,69,62,0,[],1,0

In [37]:
print(feature_name[1])
columns_to_drop=feature_name[2:26]+[feature_name[0]]
print(columns_to_drop)
df_mody=df_array[1].drop(columns_to_drop, axis=1)
df_mody

christmas
['church', 'classical', 'commercials', 'concerts', 'easter', 'fourthofjuly', 'funerals', 'graduations', 'grammys', 'halloween', 'inmovieclueless', 'inmovies', 'inplays', 'intvshows', 'karaoke', 'lullabies', 'mtvawards', 'phonecall', 'politicians', 'sportingevents', 'tvshow', 'weddings', 'wonoscars', 'wordcup', 'artistdied']

,url,weekid,week_position,song,performer,songid,instance,previous_week_position,peak_position,weeks_on_chart,year,week,jump_time,max_jump_duration,strict_rule,lenient_rule,all_time_greatest_artist,split,christmas
1024,http://www.billboard.com/charts/hot-100/2000-0...,2000-01-08,83,All I Want For Christmas Is You,Mariah Carey,All I Want For Christmas Is YouMariah Carey,1,NaN,11,19,2000,1,5,4732,85,58,1,[],1
2810,http://www.billboard.com/charts/hot-100/2010-1...,2010-12-18,79,Boots,The Killers,BootsThe Killers,1,NaN,79,1,2010,50,0,0,0,0,0,[],1
3789,http://www.billboard.com/charts/hot-100/2010-1...,2010-12-18,25,Christmas Lights,Coldplay,Christmas LightsColdplay,1,NaN,25,3,2010,50,0,0,69,59,0,[],1
8036,http://www.billboard.com/charts/hot-100/1998-0...,1998-01-10,87,Grandma Got Run Over By A Reindeer,Elmo & Patsy,Grandma Got Run Over By A ReindeerElmo & Patsy,1,NaN,87,1,1998,2,0,0,50,17,0,[],1
9574,http://www.billboard.com/charts/hot-100/1975-1...,1975-12-20,99,I Believe In Father Christmas,Greg Lake,I Believe In Father ChristmasGreg Lake,1,NaN,95,3,1975,51,0,0,0,0,0,[],1
12307,http://www.billboard.com/charts/hot-100/1958-1...,1958-12-20,57,Jingle Bell Rock,Bobby Helms,Jingle Bell RockBobby Helms,1,NaN,29,19,1958,51,5,19369,71,70,0,[],1
12983,http://www.billboard.com/charts/hot-100/2017-0...,2017-01-07,50,Last Christmas,Wham!,Last ChristmasWham!,1,NaN,41,2,2017,1,0,0,75,63,0,[],1
14888,http://www.billboard.com/charts/hot-100/2014-1...,2014-12-06,26,"Mary, Did You Know?",Pentatonix,"Mary, Did You Know?Pentatonix",1,NaN,26,7,2014,49,1,728,0,68,0,[],1
15057,http://www.billboard.com/charts/hot-100/1980-1...,1980-12-27,82,Merry Christmas In The NFL,"Willis ""The Guard"" & Vigorish","Merry Christmas In The NFLWillis ""The Guard"" &...",1,NaN,82,3,1980,52,0,0,0,0,0,[],1
15250,http://www.billboard.com/charts/hot-100/2011-1...,2011-11-05,11,Mistletoe,Justin Bieber,MistletoeJustin Bieber,1,NaN,11,10,2011,44,1,14,77,0,1,[],1
16596,http://www.billboard.com/charts/hot-100/2011-0...,2011-01-01,100,Oh Santa!,Mariah Carey,Oh Santa!Mariah Carey,1,NaN,100,1,2011,52,0,0,52,44,1,[],1
17556,http://www.billboard.com/charts/hot-100/1961-1...,1961-12-23,85,Please Come Home For Christmas,Charles Brown,Please Come Home For ChristmasCharles Brown,1,NaN,76,2,1961,51,0,0,0,37,0,[],1
17801,http://www.billboard.com/charts/hot-100/1963-1...,1963-12-14,60,Pretty Paper,Roy Orbison,Pretty PaperRoy Orbison,1,NaN,15,7,1963,50,0,0,0,37,0,[],1
18591,http://www.billboard.com/charts/hot-100/1960-1...,1960-12-10,64,Rockin' Around The Christmas Tree,Brenda Lee,Rockin' Around The Christmas TreeBrenda Lee,1,NaN,14,18,1960,49,5,18634,0,77,1,[],1
18974,http://www.billboard.com/charts/hot-100/2014-1...,2014-12-13,65,Santa Tell Me,Ariana Grande,Santa Tell MeAriana Grande,1,NaN,42,5,2014,50,0,0,79,44,0,[],1
19824,http://www.billboard.com/charts/hot-100/1960-1...,1960-12-17,64,Silent Night,Bing Crosby,Silent NightBing Crosby,1,NaN,54,2,1960,50,0,0,45,43,0,[],1
22340,http://www.billboard.com/charts/hot-100/2000-1...,2000-12-30,68,The Christmas Shoes,NewSong,The Christmas ShoesNewSong,1,NaN,42,2,2000,52,0,0,37,48,0,[],1
25844,http://www.billboard.com/charts/hot-100/1958-1...,1958-12-20,86,White Christmas,Bing Crosby,White ChristmasBing Crosby,1,NaN,12,13,1958,51,4,364,73,56,0,[],1

In [38]:
df_BingCrosby=allSong.loc[allSong['performer']=="Bing Crosby"].drop(columns_to_drop, axis=1)
df_BingCrosby

,url,weekid,week_position,song,performer,songid,instance,previous_week_position,peak_position,weeks_on_chart,year,week,jump_time,max_jump_duration,strict_rule,lenient_rule,all_time_greatest_artist,split,christmas
759,http://www.billboard.com/charts/hot-100/1960-1...,1960-12-10,79,"Adeste Fideles (Oh, Come, All Ye Faithful)",Bing Crosby,"Adeste Fideles (Oh, Come, All Ye Faithful)Bing...",1,NaN,45,3,1960,49,0,0,0,0,0,[],0
19824,http://www.billboard.com/charts/hot-100/1960-1...,1960-12-17,64,Silent Night,Bing Crosby,Silent NightBing Crosby,1,NaN,54,2,1960,50,0,0,45,43,0,[],1
25844,http://www.billboard.com/charts/hot-100/1958-1...,1958-12-20,86,White Christmas,Bing Crosby,White ChristmasBing Crosby,1,NaN,12,13,1958,51,4,364,73,56,0,[],1

In [39]:
print(feature_name[2])
columns_to_drop=feature_name[3:26]+[feature_name[0], feature_name[1]]
print(columns_to_drop)
df_mody=df_array[2].drop(columns_to_drop, axis=1)
df_mody

church
['classical', 'commercials', 'concerts', 'easter', 'fourthofjuly', 'funerals', 'graduations', 'grammys', 'halloween', 'inmovieclueless', 'inmovies', 'inplays', 'intvshows', 'karaoke', 'lullabies', 'mtvawards', 'phonecall', 'politicians', 'sportingevents', 'tvshow', 'weddings', 'wonoscars', 'wordcup', 'artistdied', 'christmas']

,url,weekid,week_position,song,performer,songid,instance,previous_week_position,peak_position,weeks_on_chart,year,week,jump_time,max_jump_duration,strict_rule,lenient_rule,all_time_greatest_artist,split,church
12284,http://www.billboard.com/charts/hot-100/1972-1...,1972-12-16,97,Jesus Is Just Alright,The Doobie Brothers,Jesus Is Just AlrightThe Doobie Brothers,1,NaN,35,11,1972,50,0,0,31,48,0,[],1
15413,http://www.billboard.com/charts/hot-100/1972-0...,1972-04-01,78,Morning Has Broken,Cat Stevens,Morning Has BrokenCat Stevens,1,NaN,6,14,1972,13,0,0,63,37,0,[],1
19824,http://www.billboard.com/charts/hot-100/1960-1...,1960-12-17,64,Silent Night,Bing Crosby,Silent NightBing Crosby,1,NaN,54,2,1960,50,0,0,45,43,0,[],1
22711,http://www.billboard.com/charts/hot-100/1974-0...,1974-02-23,71,The Lord's Prayer,Sister Janet Mead,The Lord's PrayerSister Janet Mead,1,NaN,4,13,1974,8,0,0,0,12,0,[],1

In [40]:
print(feature_name[3])
columns_to_drop=feature_name[4:26]+[feature_name[0], feature_name[1], feature_name[2]]
print(columns_to_drop)
df_mody=df_array[3].drop(columns_to_drop, axis=1)
df_mody

classical
['commercials', 'concerts', 'easter', 'fourthofjuly', 'funerals', 'graduations', 'grammys', 'halloween', 'inmovieclueless', 'inmovies', 'inplays', 'intvshows', 'karaoke', 'lullabies', 'mtvawards', 'phonecall', 'politicians', 'sportingevents', 'tvshow', 'weddings', 'wonoscars', 'wordcup', 'artistdied', 'christmas', 'church']

Empty DataFrame
Columns: [url, weekid, week_position, song, performer, songid, instance, previous_week_position, peak_position, weeks_on_chart, year, week, jump_time, max_jump_duration, strict_rule, lenient_rule, all_time_greatest_artist, split, classical]
Index: []

In [55]:
print(feature_name[4])
columns_to_drop=feature_name[5:26]+[feature_name[0], feature_name[1], feature_name[2], feature_name[3]]
print(columns_to_drop)
df_mody=df_array[4].loc[df_array[4]['strict_rule']>0].drop(columns_to_drop, axis=1)
df_mody.sort_values(by="year", ascending=True).head(20)

commercials
['concerts', 'easter', 'fourthofjuly', 'funerals', 'graduations', 'grammys', 'halloween', 'inmovieclueless', 'inmovies', 'inplays', 'intvshows', 'karaoke', 'lullabies', 'mtvawards', 'phonecall', 'politicians', 'sportingevents', 'tvshow', 'weddings', 'wonoscars', 'wordcup', 'artistdied', 'christmas', 'church', 'classical']

,url,weekid,week_position,song,performer,songid,instance,previous_week_position,peak_position,weeks_on_chart,year,week,jump_time,max_jump_duration,strict_rule,lenient_rule,all_time_greatest_artist,split,commercials
2427,http://www.billboard.com/charts/hot-100/1960-0...,1960-01-16,74,Beyond The Sea,Bobby Darin,Beyond The SeaBobby Darin,1,NaN,6,14,1960,2,0,0,58,63,1,[],1
26310,http://www.billboard.com/charts/hot-100/1960-0...,1960-05-07,97,Wonderful World,Sam Cooke,Wonderful WorldSam Cooke,1,NaN,12,15,1960,18,0,0,65,69,0,[],1
2793,http://www.billboard.com/charts/hot-100/1962-0...,1962-05-26,100,Boom Boom,John Lee Hooker,Boom BoomJohn Lee Hooker,1,NaN,60,10,1962,21,0,0,55,50,0,[],1
26175,http://www.billboard.com/charts/hot-100/1963-0...,1963-06-22,86,Wipe Out,The Surfaris,Wipe OutThe Surfaris,1,NaN,2,30,1963,25,1,1029,43,42,0,[],1
3245,http://www.billboard.com/charts/hot-100/1964-0...,1964-01-25,70,California Sun,The Rivieras,California SunThe Rivieras,1,NaN,5,10,1964,4,0,0,38,0,0,[],1
3547,http://www.billboard.com/charts/hot-100/1965-0...,1965-05-15,85,Catch The Wind,Donovan,Catch The WindDonovan,1,NaN,23,10,1965,19,0,0,58,29,0,[],1
15012,http://www.billboard.com/charts/hot-100/1966-1...,1966-11-12,65,Mellow Yellow,Donovan,Mellow YellowDonovan,1,NaN,2,12,1966,45,0,0,32,51,0,[],1
21336,http://www.billboard.com/charts/hot-100/1966-0...,1966-07-30,90,Sunshine Superman,Donovan,Sunshine SupermanDonovan,1,NaN,1,13,1966,30,0,0,57,0,0,[],1
23393,http://www.billboard.com/charts/hot-100/1966-0...,1966-01-22,74,These Boots Are Made For Walkin',Nancy Sinatra,These Boots Are Made For Walkin'Nancy Sinatra,1,NaN,1,14,1966,3,0,0,65,43,0,[],1
24199,http://www.billboard.com/charts/hot-100/1966-1...,1966-12-03,85,Try A Little Tenderness,Otis Redding,Try A Little TendernessOtis Redding,1,NaN,25,10,1966,48,0,0,62,53,0,[],1
25540,http://www.billboard.com/charts/hot-100/1966-0...,1966-04-09,100,When A Man Loves A Woman,Percy Sledge,When A Man Loves A WomanPercy Sledge,1,NaN,1,13,1966,14,0,0,65,49,0,[],1
7443,http://www.billboard.com/charts/hot-100/1966-1...,1966-12-31,100,Gimme Some Lovin',The Spencer Davis Group,Gimme Some Lovin'The Spencer Davis Group,1,NaN,7,13,1966,52,0,0,56,45,0,[],1
26417,http://www.billboard.com/charts/hot-100/1966-0...,1966-07-30,84,Wouldn't It Be Nice,The Beach Boys,Wouldn't It Be NiceThe Beach Boys,1,NaN,8,11,1966,30,0,0,71,66,1,[],1
8286,http://www.billboard.com/charts/hot-100/1967-0...,1967-02-11,79,Happy Together,The Turtles,Happy TogetherThe Turtles,1,NaN,1,15,1967,6,0,0,72,44,0,[],1
11189,http://www.billboard.com/charts/hot-100/1967-0...,1967-03-25,71,I'm A Man,The Spencer Davis Group,I'm A ManThe Spencer Davis Group,1,NaN,10,9,1967,12,0,0,41,0,0,[],1
13386,http://www.billboard.com/charts/hot-100/1967-0...,1967-01-21,85,Let's Spend The Night Together,The Rolling Stones,Let's Spend The Night TogetherThe Rolling Stones,1,NaN,55,8,1967,3,0,0,50,32,1,[],1
8273,http://www.billboard.com/charts/hot-100/1967-0...,1967-04-15,99,Happy Jack,The Who,Happy JackThe Who,1,NaN,24,9,1967,15,0,0,15,37,0,[],1
16045,http://www.billboard.com/charts/hot-100/1967-0...,1967-08-26,83,Never My Love,The Association,Never My LoveThe Association,1,NaN,2,14,1967,34,0,0,42,45,0,[],1
19576,http://www.billboard.com/charts/hot-100/1967-1...,1967-12-30,77,She's A Rainbow,The Rolling Stones,She's A RainbowThe Rolling Stones,1,NaN,25,7,1967,52,0,0,34,54,1,[],1
6080,http://www.billboard.com/charts/hot-100/1967-0...,1967-09-30,83,Everlasting Love,Robert Knight,Everlasting LoveRobert Knight,1,NaN,13,12,1967,39,0,0,15,26,0,[],1

In [50]:
allSong.loc[allSong['performer']=="John Lee Hooker"].drop(columns_to_drop, axis=1)

,url,weekid,week_position,song,performer,songid,instance,previous_week_position,peak_position,weeks_on_chart,year,week,jump_time,max_jump_duration,strict_rule,lenient_rule,all_time_greatest_artist,split,commercials
2793,http://www.billboard.com/charts/hot-100/1962-0...,1962-05-26,100,Boom Boom,John Lee Hooker,Boom BoomJohn Lee Hooker,1,NaN,60,10,1962,21,0,0,55,50,0,[],1

In [58]:
# feature_name.remove('inmovies')
a=allSong.loc[allSong['inmovies']==1].drop(feature_name, axis=1)
a.loc[a['performer']=="John Lee Hooker"]

,url,weekid,week_position,song,performer,songid,instance,previous_week_position,peak_position,weeks_on_chart,year,week,jump_time,max_jump_duration,strict_rule,lenient_rule,all_time_greatest_artist,split,inmovies
2793,http://www.billboard.com/charts/hot-100/1962-0...,1962-05-26,100,Boom Boom,John Lee Hooker,Boom BoomJohn Lee Hooker,1,NaN,60,10,1962,21,0,0,55,50,0,[],1

In [67]:
print(feature_name[5])
columns_to_drop=feature_name[6:26]+[feature_name[0], feature_name[1], feature_name[2], feature_name[3]],feature_name[4]
print(columns_to_drop)
df_mody=df_array[5].loc[df_array[5]['strict_rule']>0].drop(columns_to_drop, axis=1)
df_mody

concerts
(['easter', 'fourthofjuly', 'funerals', 'graduations', 'grammys', 'halloween', 'inmovieclueless', 'inmovies', 'inplays', 'intvshows', 'karaoke', 'lullabies', 'mtvawards', 'phonecall', 'politicians', 'sportingevents', 'tvshow', 'weddings', 'wonoscars', 'wordcup', 'artistdied', 'christmas', 'church', 'classical'], 'commercials')

TypeError: unhashable type: 'list'